spring:
  mvc:
    favicon:
      enabled: false

  devtools:
    restart:
      enabled: false


# triggering flows based on time

scheduler:
  enabled: true
  configs: uflow-app/samples/triggers

# queue listeners
processor:
  listeners:
    - processor: "debugProcessor"
      queue: "uflow-debug-processor"
      count: 1