spring:
  mvc:
    favicon:
      enabled: false

  devtools:
    restart:
      enabled: false


processor:
  listeners:
    - processor: "debugProcessor"
      queue: "uflow-debug-processor"
      count: 1